sudo: false
language: c

os:
  - linux
  - osx

osx_image: xcode10

addons:
  apt:
    sources:
      - sourceline: 'ppa:ondrej/php'
    packages:
      - libmcrypt-dev
      - libtidy-dev
      - libicu-dev
      - libzip-dev
      - php5-cli
      - re2c

env:
  global:
    - PHP_BUILD_EXTRA_MAKE_ARGUMENTS="-j2"
  matrix:
    - DEFINITION=5.2.17
    - DEFINITION=5.3.29
    - DEFINITION=5.4.45
    - DEFINITION=5.5.38
    - DEFINITION=5.6.38
    - DEFINITION=7.0.32
    - DEFINITION=7.1.23
    - DEFINITION=7.2.11
    - DEFINITION=7.3.0RC3

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" &&
          "$DEFINITION" =~ ^("5.2.".*|"5.3."[0-6])$ ]]; then
        export PHP_BUILD_CONFIGURE_OPTS="--with-libdir=lib/x86_64-linux-gnu"
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        if [[ "$DEFINITION" =~ ^("5."[23]|"5.4."([0-9]|1[0-4])$) ]]; then
            export LIBS="-lssl -lcrypto"
        fi
        brew update
        brew install re2c libmcrypt openssl libxml2 icu4c libzip
        brew upgrade pkg-config
        if [[ "$DEFINITION" == "5.2.17" ]]; then
            brew install mysql@5.7
            export PHP_BUILD_CONFIGURE_OPTS="$PHP_BUILD_CONFIGURE_OPTS --with-mysql=$(brew --prefix mysql@5.7) --with-mysqli=$(brew --prefix mysql@5.7)/bin/mysql_config --with-pdo-mysql=$(brew --prefix mysql@5.7)"
        fi
    fi

install:
  - git clone https://github.com/sstephenson/bats
  - bats/install.sh $HOME
  - export PATH=$HOME/bin:$HOME/libexec:$PATH
  - bats --version

script:
  - ./run-tests.sh $DEFINITION

after_failure:
  - cat $(ls -r /tmp/php-build*.log | head -n 1)
